export const revealConfig = {
    controls: true,
    progress: true,
    help: true,
    hash: true,
    slideNumber: 'c/t',
    fragmentInURL: true,
    touch: true,
    transition: 'zoom',
    transitionSpeed: 'default',
    backgroundTransition: 'fade',
    autoAnimateDuration: 0.6,
    autoAnimateEasing: 'ease',
    center: true,
    width: 1200,
    height: 760,
    margin: 0.04,
    minScale: 0.18,
    maxScale: 2.0,
    navigationMode: 'linear',
    pdfMaxPagesPerSlide: 1,
    pdfSeparateFragments: true,
    plugins: [RevealMarkdown, RevealHighlight, RevealNotes],
    highlight: { highlightOnLoad: true },
};
//# sourceMappingURL=reveal-config.js.map